# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: docker-web-service
spec:
  selector:
    app: docker-web
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
